##
## EPITECH PROJECT, 2022
## B-PSU-100-RUN-1-1-myls-clement-antoine.xavier
## File description:
## Makefile
##

all:
	make -C ./my/ all
	make -C ./my_printf/ all

clean:
	make -C ./my/ clean
	make -C ./my_printf/ clean

fclean:
	make -C ./my/ fclean
	make -C ./my_printf/ fclean

re:
	make -C ./my/ re
	make -C ./my_printf/ re
